server:
    port: 8080

zuul:
    routes:
        authentication:
            path: /api/authenticationService/**
            url: https://authentication-api-hackathon.herokuapp.com/
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
            