server:
    port: 8080

zuul:
    routes:
        authentication:
            path: /api/authenticationService/**
            url: https://authentication-api-hackathon.herokuapp.com
        tasks:
            path: /api/taskService/**
            url: https://task-api-hackathon.herokuapp.com/api
        api-composition:
            path: /api/compose/**
            url: https://composition-api-hackathon.herokuapp.com
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    sensitive-headers: Cookie,Set-Cookie
            